log:
  file: logs/app.log
  v115: logs/115.log
  openList: logs/openList.log
  tmdb: logs/tmdb.log
  baiduPan: logs/baidupan.log
  web: logs/web.log
  syncLogDir: logs/sync
db:
  engine: postgres
  sqliteFile: qmediasync.db
  postgresType: embedded
  postgresConfig:
    host: localhost
    port: 5432
    user: qms
    password: qms123456
    database: qms
    maxOpenConns: 25
    maxIdleConns: 25
cacheSize: 20971520
jwtSecret: Q115-STRM-JWT-TOKEN-250706
httpHost: :12333
httpsHost: :12332
strm:
  videoExt:
  - .mp4
  - .mkv
  - .avi
  - .mov
  - .wmv
  - .flv
  - .webm
  - .m4v
  - .3gp
  - .ts
  minVideoSize: 100
  metaExt:
  - .jpg
  - .jpeg
  - .png
  - .webp
  - .nfo
  - .srt
  - .ass
  - .svg
  - .sup
  - .lrc
  cron: 30 * * * *
authServer: https://api.mqfamily.top
baiDuPanAppId: QMediaSync
adminUsername: admin
adminPassword: admin123
