services:
    xiaoya-tvbox:
        ports:
            - 4567:4567
            - 5344:80
        environment:
            - ALIST_PORT=5344
        network_mode: bridge
        volumes:
            - ./xiaoya-tvbox:/data
            - ./xiaoya-tvbox/alist:/opt/alist/data
            - ./media:/emby
        restart: always
        container_name: xiaoya-tvbox
        image: haroldli/xiaoya-tvbox
        network_mode: bridge
